# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMZhusv2lqBpAEfm0GBWDDIonRFQuvUc
"""

text_a = open("1342-0.txt").read()
text_b = open("84-0.txt").read()

# ---

print(text_a[:200])

# ---

import random
random.sample(text_b, 20)

# ---

a_words = text_a.split()
b_words = text_b.split()

# ---

random.sample(a_words, 10)

# ---

random.sample(b_words, 10)

# ---

from collections import Counter
Counter(text_a).most_common(12)

# ---

Counter(a_words).most_common(12)

# ---

Counter(b_words).most_common(12)

# ---

import sys
!{sys.executable} -m pip install markovify

# ---

import markovify

# ---

generator_a = markovify.Text(text_a)

# ---

print(generator_a.make_sentence())

# ---

from google.colab import drive
drive.mount('/content/drive')